"""empty message

Revision ID: 0218164b82d9
Revises: a55bf1042a40
Create Date: 2018-06-09 11:33:31.144880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0218164b82d9'
down_revision = 'a55bf1042a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('axf_foodtypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typeid', sa.Integer(), nullable=True),
    sa.Column('typename', sa.String(length=16), nullable=True),
    sa.Column('childtypenames', sa.String(length=200), nullable=True),
    sa.Column('typesort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('axf_foodtypes')
    # ### end Alembic commands ###
